"""initial_migration

Revision ID: df194054ed21
Revises:
Create Date: 2025-02-18 19:06:23.420240

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # Add this line

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df194054ed21"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("tg_handle", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("telegram_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "role", sa.Enum("STUDENT", "TEACHER", name="userrole"), nullable=False
        ),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_telegram_id"), "user", ["telegram_id"], unique=True)
    op.create_index(op.f("ix_user_tg_handle"), "user", ["tg_handle"], unique=True)
    op.create_table(
        "homeworktask",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("COMPLETED", "PENDING", "CANCELLED", name="status"),
            nullable=False,
        ),
        sa.Column("teacher_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("student_ids", sa.ARRAY(sa.String()), nullable=False),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "submission",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("COMPLETED", "PENDING", "CANCELLED", name="status"),
            nullable=False,
        ),
        sa.Column("student_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("teacher_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "homework_task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["homework_task_id"],
            ["homeworktask.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feedback",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("COMPLETED", "PENDING", "CANCELLED", name="status"),
            nullable=False,
        ),
        sa.Column("student_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("teacher_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("submission_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submission.id"],
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feedback")
    op.drop_table("submission")
    op.drop_table("homeworktask")
    op.drop_index(op.f("ix_user_tg_handle"), table_name="user")
    op.drop_index(op.f("ix_user_telegram_id"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
